apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: todo-app
  description: A simple Todo app with REST API
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: adansa
  providesApis:
    - todo-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: todo-api
  description: API for Todo app
spec:
  type: openapi
  lifecycle: experimental
  owner: adansa
  definition:
    $text: http://localhost:8000/swagger.json  # Update with actual URL in production
